package App.Model;
// Generated 2016-03-30 18:52:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name = "Color", schema = "dbo", catalog = "koraliki")
public class Color implements java.io.Serializable {

	private int idColor;
	private String colorName;
	private String colorCode;
	private String colorFamily;
	private Set<Beads> beads = new HashSet<Beads>(0);

	public Color() {
	}

	public Color(int idColor, String colorName) {
		this.idColor = idColor;
		this.colorName = colorName;
	}

	public Color(int idColor, String colorName, String colorCode, String colorFamily, Set<Beads> beads) {
		this.idColor = idColor;
		this.colorName = colorName;
		this.colorCode = colorCode;
		this.colorFamily = colorFamily;
		this.beads = beads;
	}

	@Id

	@Column(name = "id_color", unique = true, nullable = false)
	public int getIdColor() {
		return this.idColor;
	}

	public void setIdColor(int idColor) {
		this.idColor = idColor;
	}

	@Column(name = "color_name", nullable = false)
	public String getColorName() {
		return this.colorName;
	}

	public void setColorName(String colorName) {
		this.colorName = colorName;
	}

	@Column(name = "color_code", length = 50)
	public String getColorCode() {
		return this.colorCode;
	}

	public void setColorCode(String colorCode) {
		this.colorCode = colorCode;
	}

	@Column(name = "color_family", length = 50)
	public String getColorFamily() {
		return this.colorFamily;
	}

	public void setColorFamily(String colorFamily) {
		this.colorFamily = colorFamily;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	public Set<Beads> getBeads() {
		return this.beads;
	}

	public void setBeads(Set<Beads> beads) {
		this.beads = beads;
	}

}
