package App.Model;
// Generated 2016-03-30 18:52:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Finish generated by hbm2java
 */
@Entity
@Table(name = "Finish", schema = "dbo", catalog = "koraliki")
public class Finish implements java.io.Serializable {

	private int idFinish;
	private String finishName;
	private Set<FinishBeads> finishBeads = new HashSet<FinishBeads>(0);

	public Finish() {
	}

	public Finish(int idFinish) {
		this.idFinish = idFinish;
	}

	public Finish(int idFinish, String finishName, Set<FinishBeads> finishBeads) {
		this.idFinish = idFinish;
		this.finishName = finishName;
		this.finishBeads = finishBeads;
	}

	@Id

	@Column(name = "id_finish", unique = true, nullable = false)
	public int getIdFinish() {
		return this.idFinish;
	}

	public void setIdFinish(int idFinish) {
		this.idFinish = idFinish;
	}

	@Column(name = "finish_name")
	public String getFinishName() {
		return this.finishName;
	}

	public void setFinishName(String finishName) {
		this.finishName = finishName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "finish")
	public Set<FinishBeads> getFinishBeads() {
		return this.finishBeads;
	}

	public void setFinishBeads(Set<FinishBeads> finishBeads) {
		this.finishBeads = finishBeads;
	}

}
