package App.Model;
// Generated 2016-03-30 18:52:05 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FinishBeadsId generated by hbm2java
 */
@Embeddable
public class FinishBeadsId implements java.io.Serializable {

	private Integer idFinish;
	private Integer idBead;

	public FinishBeadsId() {
	}

	public FinishBeadsId(Integer idFinish, Integer idBead) {
		this.idFinish = idFinish;
		this.idBead = idBead;
	}

	@Column(name = "id_finish")
	public Integer getIdFinish() {
		return this.idFinish;
	}

	public void setIdFinish(Integer idFinish) {
		this.idFinish = idFinish;
	}

	@Column(name = "id_bead")
	public Integer getIdBead() {
		return this.idBead;
	}

	public void setIdBead(Integer idBead) {
		this.idBead = idBead;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FinishBeadsId))
			return false;
		FinishBeadsId castOther = (FinishBeadsId) other;

		return ((this.getIdFinish() == castOther.getIdFinish()) || (this.getIdFinish() != null
				&& castOther.getIdFinish() != null && this.getIdFinish().equals(castOther.getIdFinish())))
				&& ((this.getIdBead() == castOther.getIdBead()) || (this.getIdBead() != null
						&& castOther.getIdBead() != null && this.getIdBead().equals(castOther.getIdBead())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdFinish() == null ? 0 : this.getIdFinish().hashCode());
		result = 37 * result + (getIdBead() == null ? 0 : this.getIdBead().hashCode());
		return result;
	}

}
