package App.Model;
// Generated 2016-03-30 18:52:05 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FinishBeads generated by hbm2java
 */
@Entity
@Table(name = "Finish_Beads", schema = "dbo", catalog = "koraliki")
public class FinishBeads implements java.io.Serializable {

	private FinishBeadsId id;
	private Beads beads;
	private Finish finish;

	public FinishBeads() {
	}

	public FinishBeads(FinishBeadsId id) {
		this.id = id;
	}

	public FinishBeads(FinishBeadsId id, Beads beads, Finish finish) {
		this.id = id;
		this.beads = beads;
		this.finish = finish;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idFinish", column = @Column(name = "id_finish")),
			@AttributeOverride(name = "idBead", column = @Column(name = "id_bead")) })
	public FinishBeadsId getId() {
		return this.id;
	}

	public void setId(FinishBeadsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bead", insertable = false, updatable = false)
	public Beads getBeads() {
		return this.beads;
	}

	public void setBeads(Beads beads) {
		this.beads = beads;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_finish", insertable = false, updatable = false)
	public Finish getFinish() {
		return this.finish;
	}

	public void setFinish(Finish finish) {
		this.finish = finish;
	}

}
